### ISSUE TITLE
Mongo.Topology terminate with bad return value

### ISSUE THREAD

**Issue by wangxingfred** [zookzook/elixir-mongodb-driver#60] opened 2020-05-22 03:52 UTC
Hi, I'm getting this error while testing mongodb server disconnection

```elixir
18:00:28.448 [error] GenServer Mongo terminating
** (stop) bad return value: :error
Last message (from #PID<0.386.0>): {:checkout_session, :read, :implicit, []}

    (stdlib 3.12) gen.erl:167: :gen.do_call/4
    (elixir 1.10.2) lib/gen_server.ex:1020: GenServer.call/3
    (mongodb_driver 0.6.4) lib/mongo/session.ex:157: Mongo.Session.start_implicit_session/3
    (mongodb_driver 0.6.4) lib/mongo/cursor.ex:47: anonymous fn/3 in Enumerable.Mongo.Cursor.start_fun/4
    (elixir 1.10.2) lib/stream.ex:1407: anonymous fn/5 in Stream.resource/3
    (elixir 1.10.2) lib/enum.ex:3457: Enum.slice_enum/4
    (elixir 1.10.2) lib/enum.ex:398: Enum.at/3
    (stdlib 3.12) erl_eval.erl:680: :erl_eval.do_apply/6
** (exit) exited in: GenServer.call(Mongo, {:checkout_session, :read, :implicit, []}, 5000)
    ** (EXIT) bad return value: :error
    (elixir 1.10.2) lib/gen_server.ex:1023: GenServer.call/3
    (mongodb_driver 0.6.4) lib/mongo/session.ex:157: Mongo.Session.start_implicit_session/3
    (mongodb_driver 0.6.4) lib/mongo/cursor.ex:47: anonymous fn/3 in Enumerable.Mongo.Cursor.start_fun/4
    (elixir 1.10.2) lib/stream.ex:1407: anonymous fn/5 in Stream.resource/3
    (elixir 1.10.2) lib/enum.ex:3457: Enum.slice_enum/4
    (elixir 1.10.2) lib/enum.ex:398: Enum.at/3
``

**Comment by zookzook** [comment] 2020-05-22 05:51
Can you provide more information?

What kind of deployment do you use? Replica-Set? Standalone?

What is the expected behavior?

Source code template?

**Comment by wangxingfred** [comment] 2020-05-25 03:07
### Deployment
Standalone, MongoDB 4.2.1 Community


### Steps to reproduce
- Connect to a remote standalone mongodb server.
```elixir
iex> Mongo.start_link([name: Mongo, database: "dev", hostname: "192.168.1.27"])
```
- Cut off network connection. (Disable Ethernet adapters)
- Execute a mongo request.
```elixir
iex> Mongo.find_one(Mongo, "dev", [])
```
- Then you see terminating message

### Expected behaviour
maybe return an error from Mongo.find_one instead of connection process crash

**Comment by zookzook** [comment] 2020-05-25 09:20
I added a better error handling. You can run you test case with the master code again:

```elixir
{:mongodb_driver, git: "https://github.com/zookzook/elixir-mongodb-driver.git"}
```

I was not able to reproduce the error, because the connection pools returns an error. Therefore I checked the code and found a possible situation where the GenServer function returns `:error` instead of `{:reply, error, state}' tuple.

I wrapped this case into `error -> {:reply, error, state}`.

**Comment by zookzook** [comment] 2020-05-25 09:21
Please give feedback to close this issue.

**Comment by wangxingfred** [comment] 2020-05-25 09:43
Got following error instead
```elixir
{:error,
 %Mongo.Error{
   code: nil,
   error_labels: nil,
   host: nil,
   message: "Unknow result :error while calling Topology.checkout_session/4",
   resumable: false,
   retryable_reads: nil,
   retryable_writes: nil
 }}
```

Seems the result `:error` comes from `Mongo.Topology.get_connection`, can we make this message more specific?

**Comment by zookzook** [comment] 2020-05-25 10:09
> Seems the result :error comes from Mongo.Topology.get_connection, can we make this message more specific?

The error comes from `Map.fetch(pools, address)` in your test case. I will change the code a little bit to extract the cause.

**Comment by zookzook** [comment] 2020-05-25 10:14
I changed the code into this:

```
  defp get_connection(nil, _state), do: nil
  defp get_connection(address, %{connection_pools: pools}) do
    case Map.fetch(pools, address) do
      :error -> {:error, Mongo.Error.exception("The server #{inspect address} is no longer available")}
      conn   -> conn
    end
  end
```

**Comment by zookzook** [comment] 2020-05-25 10:15
I pushed the code. You can try it again.

**Comment by wangxingfred** [comment] 2020-05-26 01:57
Nothing changed, no such commit on master either.

**Comment by zookzook** [comment] 2020-05-26 06:46
Sorry, forgot to push changes!

**Comment by wangxingfred** [comment] 2020-05-26 08:46
When I call `Mongo.find_one` immediately after network disconnection, `(EXIT) normal` happend, is that expected?
```
iex(53)> Mongo.find_one(Mongo, "dev", [])
16:29:10.533 [error] Mongo.MongoDBConnection (#PID<0.247.0>) disconnected: ** (Mongo.Error) 192.168.1.27:27017 tcp send: unknown POSIX error - :closed (module=DBConnection.Connection function=disconnect/2 line=125 )

16:29:10.534 [error] Mongo.MongoDBConnection (#PID<0.247.0>) failed to connect: ** (Mongo.Error) 192.168.1.27:27017 tcp connect: network is unreachable - :enetunreach (module=DBConnection.Connection function=connect/2 line=90 )

16:29:10.537 [error] Mongo.MongoDBConnection (#PID<0.294.0>) failed to connect: ** (Mongo.Error) 192.168.1.27:27017 tcp connect: network is unreachable - :enetunreach (module=DBConnection.Connection function=connect/2 line=90 )

** (exit) exited in: DBConnection.Holder.checkout(#PID<0.267.0>, [timeout: 15000])
    ** (EXIT) normal
    (db_connection 2.2.1) lib/db_connection/holder.ex:86: DBConnection.Holder.checkout/2
    (db_connection 2.2.1) lib/db_connection.ex:1029: DBConnection.checkout/3
    (db_connection 2.2.1) lib/db_connection.ex:1340: DBConnection.run/6
    (db_connection 2.2.1) lib/db_connection.ex:595: DBConnection.execute/4
    (mongodb_driver 0.7.0) lib/mongo.ex:729: Mongo.exec_command_session/3
    (mongodb_driver 0.7.0) lib/mongo/stream.ex:23: Mongo.Stream.new/3
    (mongodb_driver 0.7.0) lib/mongo.ex:676: Mongo.find/4
    (mongodb_driver 0.7.0) lib/mongo.ex:703: Mongo.find_one/4
```

Two second later, I call `Mongo.find_one` again, `Mongo.Error` returned
```
iex(59)> Mongo.find_one(Mongo, "dev", [])
{:error,
 %Mongo.Error{
   code: nil,
   error_labels: nil,
   host: nil,
   message: "The server \"192.168.1.27:27017\" is no longer available",
   resumable: false,
   retryable_reads: nil,
   retryable_writes: nil
 }}
```

**Comment by zookzook** [comment] 2020-05-26 09:23
Yes, this is quite normal. But you should avoid to start the process for the connection by  calling `Mongo.start_link([name: Mongo, database: "dev", hostname: "192.168.1.27"])`. For regular application you use a `Supervisor` and a replica set of three nodes. If the connections are lost, the Supervisor keeps the Mongo process alive.

**Comment by wangxingfred** [comment] 2020-05-27 03:40
Got it. Thank you!!

**Comment by wangxingfred** [comment] 2020-05-28 08:35
I found the same `bad return value` issue in  `Mongo.Topology.select_server`

**Comment by zookzook** [comment] 2020-05-29 10:46
Can you quote the source code, where to find it?

**Comment by wangxingfred** [comment] 2020-06-01 08:45
Mongo.Topology.select_server
```elixir
  def handle_call({:select_server, cmd_type, opts}, from, %{:topology => topology, :waiting_pids => waiting} = state) do
    case TopologyDescription.select_servers(topology, cmd_type, opts) do
      :empty ->
        Mongo.Events.notify(%ServerSelectionEmptyEvent{action: :select_server, cmd_type: cmd_type, topology: topology, opts: opts})
        {:noreply, %{state | waiting_pids: [from | waiting]}} ## no servers available, wait for connection

      {:ok, {address, _opts}} ->
        with {:ok, connection} <- get_connection(address, state) do
          {:reply, {:ok, connection}, state}
        end
      error ->
        {:reply, error, state} ## in case of an error, just return the error
    end
  end
```

Missing an `else` after `with {:ok, connection} <- get_connection(address, state) do`.

**Comment by zookzook** [comment] 2020-06-05 06:08
Thank you. I fixed it.

**Closed** 2020-06-05 06:08 UTC
Labels: bug

**Comment by wangxingfred** [comment] 2020-06-08 11:39
😄
