### ISSUE TITLE
After creating Sharder Cluster with tags cant update document

### ISSUE THREAD

**Issue by MIIIG** [zookzook/elixir-mongodb-driver#176] opened 2023-02-01 16:21 UTC
`  def create(fields) do
    c = Repo.insert!(Contact.new())
    Repo.update(Map.merge(c, fields))
  end`

I'm updated driver to 1.0.2 and trying to add opts, but catch undefined function error  `Repo.update/2 is undefined`, but i find in deps in module mongo.repo the 2 arity function

Thanks!

**Comment by zookzook** [comment] 2023-02-01 16:27
Mmm...maybe try the master branch. It seems, that the options parameter was added in the last commit https://github.com/zookzook/elixir-mongodb-driver/pull/172

**Comment by MIIIG** [comment] 2023-02-02 17:00
First time using link to git and branch name, works great! But i still cant update document in shard cluster,  because for that i need to create tags in document and using them  in filter field for Repo.update.

**Comment by MIIIG** [comment] 2023-02-03 08:43
i am defined new() in collection with putting my attributes, thnks

**Comment by zookzook** [comment] 2023-02-05 08:28
So the issue is solved? I close the issue for now. Feel free to open a new one if needed.

**Closed by zookzook** 2023-02-05 08:28 UTC
