### ISSUE TITLE
Mongo timeout value only works if passed directly to query

### ISSUE THREAD

**Issue by snurges** [zookzook/elixir-mongodb-driver#214] opened 2023-09-21 13:51 UTC
Hey! 

For me it seems that the only way to increase default Mongo timeout limit is to add it as a parameter in the query, for example like this: `Mongo.find(:mongo, "collection", %{}, timeout: 60_000)`. If I just add the timeout param to `Mongo.start_link()` and then later make a query it uses the default timeout value (15 sec).

The exact timeout error I receive is this: `Mongo.MongoDBConnection (#PID<0.6890.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.18881.3561> timed out because it queued and checked out the connection for longer than 15000ms`.

This is the config that I'm using:
```
config :fraud_engine, Mongo,
  name: :mongo,
  url: "#{System.get_env("MONGO_URL")}",
  timeout: 60_000,
  connect_timeout: 60_000,
  checkout_timeout: 60_000,
  pool_timeout: 60_000,
  pool_size: 20
```

And this is how it looks in `application.ex`:
```
children = [
  ...
  %{id: :mongo, start: {Mongo, :start_link, [Application.get_env(:my_app, Mongo)]}}
  ...
]

Supervisor.start_link(children, opts)
```
I have verified that the correct config values are retrieved in `Application.get_env(:my_app, Mongo)` call.

I'm not sure if this is a bug or not but any help would be appreciated!

**Comment by zookzook** [comment] 2023-09-22 06:35
Hey!

One question: does the URL contain a timeout?

```elixir
%{id: :mongo, start: {Mongo, :start_link, [Application.get_env(: fraud_engine, Mongo)]}}
```

I guess, you mean `: fraud_engine` instead of `:my_app`?

**Comment by snurges** [comment] 2023-09-22 06:53
Hey, sorry forgot to substitute `:fraud_engine` to `:my_app` in the example. 

The URL does not contain a timeout, it looks like this `mongodb://root:example@localhost:27018/admin`.

**Comment by zookzook** [comment] 2023-09-22 07:10
I used the same configuration above and it seems to work. For me, it is not reproducible. You can check out the master branch and edit the following line in the `lib/mongo/mongo_db_connection.ex` file:
![image](https://github.com/zookzook/elixir-mongodb-driver/assets/221964/80a11008-140e-40a3-a05c-f3bb29af7d86)

This prints the timeout value to the stdout. Then you can see, what value is used. In my case, the specified `60_000` is always used.

**Comment by snurges** [comment] 2023-09-25 10:50
Hey, thanks for your reply. Indeed, when I log it there it works as you mentioned. 

I also tried logging in the actual place I get the error in production, which is in `(db_connection 2.5.0) lib/db_connection.ex:1432: DBConnection.run_execute/5`, like this:

```elixir
  defp run_execute(conn, query, params, meter, opts) do
    %DBConnection{pool_ref: pool_ref} = conn
    meter = event(meter, :execute)

    IO.inspect(opts, label: :opts)
```

When I open up iex and run `Mongo.find_one(:mongo, "Collection", %{}, timeout: 60000)`, it prints out `opts: [batch_size: 1, timeout: 60000]`. But when I don't specify timeout in query and just run `Mongo.find_one(:mongo, "Collection", %{})`, it prints out `opts: [batch_size: 1]`. So based on this it seems to me that the timeout option gets lost somewhere but I'm not sure if it is an issue in driver or `db_connection` itself. It might also be that this is expected and I'm looking at it wrong 🤔

**Comment by snurges** [comment] 2023-09-25 11:44
For reference, this is the actual error I get in production:
```elixir
Mongo.MongoDBConnection (#PID<0.6886.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5522.8060> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.5522.8060> was at location:

    :prim_inet.recv0/3
    (mongodb_driver 1.2.0) lib/mongo_db_connection/utils.ex:105: Mongo.MongoDBConnection.Utils.recv_data/3
    (mongodb_driver 1.2.0) lib/mongo_db_connection/utils.ex:21: Mongo.MongoDBConnection.Utils.post_request/3
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (mongodb_driver 1.2.0) lib/mongo/mongo_db_connection.ex:356: Mongo.MongoDBConnection.send_command/3
    (mongodb_driver 1.2.0) lib/mongo/mongo_db_connection.ex:101: Mongo.MongoDBConnection.handle_execute/4
    (db_connection 2.5.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.5.0) lib/db_connection.ex:1432: DBConnection.run_execute/5
```

**Comment by snurges** [comment] 2023-09-25 11:48
Now that I look at it, I realized that it ends up in `lib/mongo/mongo_db_connection.ex` in `send_command/3` anyway (where it works as expected), so you can disregard my previous comments 🤦

**Comment by zookzook** [comment] 2023-09-25 12:49
Ok! Maybe the `DBConnection.run_execute/5` is complaining about the timeout. This could be the reason. If you run a query the driver doesn't use the predefined timeout and therefore the DBConnection is using the 15_000 ms.

**Comment by zookzook** [comment] 2023-09-25 13:41
I think it is a bug because the DBConnection module times out and not the underlying TCP connection. I will fix it!

**Comment by zookzook** [comment] 2023-09-25 15:47
You can try this PR: https://github.com/zookzook/elixir-mongodb-driver/pull/215 

The interesting point is, that the `:timeout` option is not recognized by the underlying `DBConnection` module. The driver needs to update the timeout options for each query/update unless the client provides its own timeout value.

**Comment by snurges** [comment] 2023-09-28 09:01
I tried this out and the issue seems to be fixed now, thank you!

**Comment by zookzook** [comment] 2023-09-29 12:12
Thanks for the response. The PR is merged to the master branch and in a few days I will release a new version.

**Closed by zookzook** 2023-09-29 12:12 UTC
Labels: bug
