### ISSUE TITLE
Replica set connection

### ISSUE THREAD

**Issue by p-mongo** [zookzook/elixir-mongodb-driver#63] opened 2020-05-29 21:38 UTC
I have a replica set I am connecting to and performing a simple query on in an infinite loop. Then I step down the primary in the replica set.

Each time I do this my reader is stuck receiving the `not master` error and does not seem to recover.

How do I get the reader to talk to the new primary?

I tried the following connection establishment options:

<pre>

    {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:34420,localhost:34421,localhost:34422/load",
      pool_size: 10)

    {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:34420,localhost:34421,localhost:34422/load?replicaSet=ruby-driver-rs",
      pool_size: 10)

    {:ok, conn} = Mongo.start_link(database: "load", seeds: ["localhost:34420","localhost:34421","localhost:34422"],
      pool_size: 10)
</pre>

And my reader looks like this:

<pre>
    cursor = Mongo.find(conn, "data",
      %{"$and" => [%{counter: 1234}]}
    )
    
    case cursor do
      {:error, error} ->
          IO.inspect(error)
      _ ->
          cursor
          |> Enum.to_list()
          |> Enum.count
          
    end
</pre>

I get:

<pre>
%Mongo.Error{
  code: 13435,
  error_labels: [],
  host: nil,
  message: "not master and slaveOk=false",
  resumable: true,
  retryable_reads: true,
  retryable_writes: true
}
</pre>

**Comment by zookzook** [comment] 2020-05-29 21:59
I will check it. Local time is 23:56 😜, maybe you can provide the full source code, so I can reproduce the error.

**Comment by p-mongo** [comment] 2020-05-29 22:09
Thanks and no worries. I copied the application into https://github.com/p-mongo/tests/blob/master/ex-63/lib/reader.ex, if needed I can remove parts irrelevant to this issue.

**Comment by p-mongo** [comment] 2020-05-29 22:51
I think I see what the issue is - the topology is updated by the monitor and hence it takes up to 10 seconds for the application to recover. In these 10 seconds the reads are failing with the not master error.

The missing functionality in the Elixir driver appears to be marking the server unknown and triggering  an immediate server check when an application operation receives a not master error.

This behavior is described [here](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#not-master-and-node-is-recovering).

**Comment by p-mongo** [comment] 2020-06-04 16:23
To make this ticket perhaps more actionable, the readme says this driver supports read retries but it is my impression that for read retries to be meaningful the driver must immediately mark the failing server unknown (otherwise the read retry would go to the same server that just failed, and would fail again). Am I missing something or what read retry scenarios are expected to work (in the sense that the server returns an error, but this error is not visible by the application)?

**Comment by zookzook** [comment] 2020-06-04 16:31
Sorry for the delay. But I'm currently a little busy. But I want doing some on next Friday.

**Comment by zookzook** [comment] 2020-06-05 06:50
I think, we need something like back pressure, because if every fetch/insert operation forces to call `is_master` we will flood the server with useless requests, because it take a bit time for the election of the new master.

**Comment by zookzook** [comment] 2020-06-05 07:25
>  Am I missing something or what read retry scenarios are expected to work (in the sense that the server returns an error, but this error is not visible by the application)?

Read retry are defined for specific range of errors. And not master is not included. And the read retries are only one time retried. So, in your test case you never see a successful read retry.

**Comment by p-mongo** [comment] 2020-06-06 16:00
> I think, we need something like back pressure, because if every fetch/insert operation forces to call is_master we will flood the server with useless requests, because it take a bit time for the election of the new master.

My understanding of how this is meant to be handled is as follows:

1.  Prior to each operation (read/write), server selection must be performed. In case of primary read, we need  a primary.
2. When a read fails due to not master, the respective server must be immediately marked unknown.
3. The read is then retried, but the retry goes through server selection. Since the former primary is currently unknown, there is no primary. Server selection must wait for up to server selection timeout to locate a primary before returning.

The current default timeouts in the Ruby driver are 30 seconds for server selection (which I would like to reduce to 15-20 seconds) and the heartbeat interval is 10 seconds. Meaning if the servers are polled every 10 seconds by the monitor the application will experience a pause up to 10 seconds, then the driver should locate the new primary, and be able to issue the read retry to the new primary. No errors should be seen by the application.

In practice when server selection can't find a suitable server, it requests an immediate rescan of all servers, which means each server will be (attempted to be) scanned every minimum interval between scans (fixed at 500 ms). So normally the application wouldn't pause for the heartbeat interval. I haven't been able to find where in the Elixir driver an immediate scan can be requested, is something like this implemented?

**Comment by zookzook** [comment] 2020-06-09 06:15
Thank you for your detailed description. You could look at the Topologic, Mongo.TopologyDescription and Monitor module. From your description it looks like the state of starting the Topologic. 

There is a module attribute defined, but not used
`# not used @min_heartbeat_frequency_ms 500`

I need to explore the code here, because I didn't write this part. Maybe you can investigate some efforts as well. PR are always welcome 👍

So, it is a good time to update the code.

**Comment by scottmessinger** [comment] 2021-03-10 14:41
Just curious, @zookzook -- is this a problem that this driver inherited from the original Elixir MongoDB driver or is this related to the improvements you've made? The reason I ask is we're considering switching over to this driver, but want to know if this a new issue we'd need to tackle or an existing one? In our use of the original driver, we've not seen our MongoDB queries fail for up to 10 seconds when a primary fail over happens.

**Comment by p-mongo** [comment] 2021-03-10 15:05
@scottmessinger  I am very much a  newcomer to Elixir but as I understand it the following alternate scenario is possible:

- The driver returns a read (let's say) error.
- - This error is seen by your application.
- Your application then tears down everything database-related and creates a new client.
- The new client performs server discovery before executing operations.
In this case there won't be a 10 second period where your application would continue to receive errors, but it would have received the first error (which is supposed to be transparently retried by the driver) and you would have to recreate clients during failures, which is also not supposed to be needed.

**Comment by zookzook** [comment] 2021-03-12 22:46
I guess, it is inherited from the original Elixir MongoDB driver. But I'm curious, why a primary fail over happens? 10 seconds can be a lot of time. I think it is okay, to receive errors (regardless of the cause), because the driver is not able to handle all possibilities.

Suppose we have a producer capable of creating 1000 records per second. How should the driver react within the 10 seconds? Should it buffer all 10_000 records? And what happens if the buffer is not large enough? I think the real problem (failure of the primary db) is only postponed.

So it is easier for the driver to tell the client the truth about the result of the operation: the primary DB is unreachable right now and the client must then decide how to deal with it.

**Comment by zookzook** [comment] 2021-03-12 22:59
The retry logic described by the MongoDB specification is already too much in my opinion. The idea is nice but, it adds too much complexity to the code of the driver. It sounds more like it's just postponing a problem. 

One must also consider the circumstances: how often does such an exceptional situation occur in comparison to normality? Is it an exception or a regularity? In case of regularity then the client should decide about it. For the producer example before, back-pressure would be the better alternative.

**Comment by zookzook** [comment] 2021-03-12 23:04
And finally, the problem is very difficult to test. My old company never had such a problem. The primary DB runs and runs and runs. So it is really hard to describe the behavior of such a situation in a concrete test case. herefore, it is not sufficient to simply terminate the primary db, even if it seems that way. What happens if the primary db is not the problem, but the network is?

**Comment by p-mongo** [comment] 2021-03-16 14:33
Note also that if the driver surfaces an error to the application, and then the application destroys the client instance, recreates it, waits for server discovery for all servers, and *then* retries the operation, the application would be unavailable for longer (and would do more work) than if the driver retried the error transparently to the application.

I suppose the question of what happens when the application is pushing massive amounts of data to the database is valid, but surely there are real throttling solutions to this problem that simply pause activity for the minimum required time rather than creating a longer-than-necessary outage.

**Comment by zookzook** [comment] 2021-08-22 10:49
After a year I try to start to fix it. So, I grab the PR #71 and take a look on it. It requires some changes to handle the situation, when the primary db is changing. The ChangeStreams and the Stream module needs some modification. But we can simulate the situation via the `failCommand` feature. The biggest challenge is resource management in streams when the connection changes.

**Comment by p-mongo** [comment] 2021-08-22 18:46
The spec tests for retryable writes use a more obscure fail point called `onPrimaryTransactionalWrite` (because it was implemented in earlier servers than `failCommand`) but I imagine `failCommand` will also work and may well be easier to use.

**Comment by zookzook** [comment] 2021-08-28 12:04
Now all test units pass. ChangeStream is fixed. You can use the [feature/replica-set-connection](https://github.com/zookzook/elixir-mongodb-driver/tree/feature/replica-set-connection) branch to test.

**Comment by zookzook** [comment] 2021-09-18 09:43
I checked the behaviour with the "reader.ex" file and called on the primary:

`db.adminCommand({replSetStepDown: 30})`

and I saw only the error message one time:

```elixir

11:38:02.431 [info] Error: %Mongo.Error{code: 13435, error_labels: [], host: nil, message: "not master and slaveOk=false", not_writable_primary_or_recovering: true, resumable: true, retryable_reads: true, retryable_writes: true} (module=Reader function=read/2 line=21 )

11:38:02.431 [info] Called with error (module=Reader function=read/2 line=13 )
```

**Comment by zookzook** [comment] 2021-09-18 09:46
It's merged into the master branch.

**Closed by zookzook** 2021-09-18 09:46 UTC
Labels: bug, enhancement
